spring:
  application:
    name: mooda
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mooda_db
    username: postgres
    password: mysecurepassword
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: mysecurepassword
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/mooda_db
    user: postgres
    password: mysecurepassword
    driver-class-name: org.postgresql.Driver

mooda:
  security:
    jwt:
      secret: dev-secret-change
      access-min: 15
      refresh-days: 180
      verify-hours: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    cors:
      allowed-origins: "*"
  auth:
    verify-url-base: http://localhost:8010/api/v1/auth/verify
    debug-expose-token: false
  share:
    png-enabled: false
  stats:
    min-sample-country: 100

server:
  port: 8010
