spring:
  application:
    name: mooda
  main:
    web-application-type: reactive
  r2dbc:
    url: ${DB_R2DBC_URL:r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mooda_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecurepassword}
    pool:
      initial-size: ${DB_POOL_INITIAL_SIZE:5}
      max-size: ${DB_POOL_MAX_SIZE:20}
      max-idle-time: ${DB_POOL_MAX_IDLE:30m}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:mysecurepassword}
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
          connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_SMTP_TIMEOUT:5000}
          writetimeout: ${MAIL_SMTP_WRITETIMEOUT:5000}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${DB_JDBC_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mooda_db}}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecurepassword}
    driver-class-name: org.postgresql.Driver

mooda:
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret-change}
      access-min: ${JWT_ACCESS_MINUTES:15}
      refresh-days: ${JWT_REFRESH_DAYS:180}
      verify-hours: ${JWT_VERIFY_HOURS:24}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}

app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  auth:
    verify-url-base: ${VERIFY_URL_BASE:http://localhost:8010/api/v1/auth/verify}
    debug-expose-token: ${DEBUG_EXPOSE_TOKEN:false}
  mail:
    enabled: ${MAIL_ENABLED:true}
    from: Mooda Verification Service<verify@mooda.fun>
    ses:
      region: ${AWS_REGION:eu-north-1}
      configuration-set: ${SES_CONFIGURATION_SET:my-first-configuration-set}
      access-key-id: ${AWS_ACCESS_KEY_ID:}
      secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
      session-token: ${AWS_SESSION_TOKEN:}
  share:
    png-enabled: ${SHARE_PNG_ENABLED:false}
  stats:
    min-sample-country: ${STATS_MIN_SAMPLE_COUNTRY:100}

server:
  port: ${PORT:8010}
